"""added event enum

Revision ID: adffd0070a17
Revises: e67a6598cbd7
Create Date: 2025-12-29 20:08:21.331417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adffd0070a17'
down_revision: Union[str, Sequence[str], None] = 'e67a6598cbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_table', sa.Column('event_cover_image', sa.String(), nullable=True))
    op.add_column('events_table', sa.Column('event_visibility_type', sa.Enum('TARGET_ONLY', 'PUBLIC', name='event_visibility_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_table', 'event_visibility_type')
    op.drop_column('events_table', 'event_cover_image')
    # ### end Alembic commands ###
