"""program name made unique

Revision ID: 3546a82af5d0
Revises: a931123a8191
Create Date: 2025-12-28 11:56:57.598067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3546a82af5d0'
down_revision: Union[str, Sequence[str], None] = 'a931123a8191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_programs_table_program_name'), 'programs_table', ['program_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programs_table_program_name'), table_name='programs_table')
    # ### end Alembic commands ###
