"""added pg trm

Revision ID: e67a6598cbd7
Revises: ada003342b67
Create Date: 2025-12-28 12:59:54.434462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67a6598cbd7'
down_revision: Union[str, Sequence[str], None] = 'ada003342b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_program_name_trgm', 'programs_table', ['program_name'], unique=False, postgresql_using='gist', postgresql_ops={'program_name': 'gist_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_name_trgm', table_name='programs_table', postgresql_using='gist', postgresql_ops={'program_name': 'gist_trgm_ops'})
    # ### end Alembic commands ###
