"""rename audience into event audience

Revision ID: 6cea1f294560
Revises: 2c283af0a53e
Create Date: 2025-12-31 11:58:13.906766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cea1f294560'
down_revision: Union[str, Sequence[str], None] = '2c283af0a53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_audience_table',
    sa.Column('event_audience_id', sa.UUID(), nullable=False),
    sa.Column('event_audience_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('event_audience_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_audience_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs_table.program_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_audience_id')
    )
    op.drop_table('audience_table')
    op.add_column('event_media_table', sa.Column('event_media_id', sa.UUID(), nullable=False))
    op.add_column('event_media_table', sa.Column('event_media_file_url', sa.String(length=500), nullable=False))
    op.add_column('event_media_table', sa.Column('event_media_type', sa.String(length=20), nullable=False))
    op.add_column('event_media_table', sa.Column('event_media_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('event_media_table', 'media_type')
    op.drop_column('event_media_table', 'media_file_url')
    op.drop_column('event_media_table', 'media_created_at')
    op.drop_column('event_media_table', 'media_id')
    op.drop_constraint(op.f('events_table_event_target_program_id_fkey'), 'events_table', type_='foreignkey')
    op.drop_column('events_table', 'event_target_program_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_table', sa.Column('event_target_program_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_table_event_target_program_id_fkey'), 'events_table', 'programs_table', ['event_target_program_id'], ['program_id'], ondelete='SET NULL')
    op.add_column('event_media_table', sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('event_media_table', sa.Column('media_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('event_media_table', sa.Column('media_file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('event_media_table', sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('event_media_table', 'event_media_created_at')
    op.drop_column('event_media_table', 'event_media_type')
    op.drop_column('event_media_table', 'event_media_file_url')
    op.drop_column('event_media_table', 'event_media_id')
    op.create_table('audience_table',
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('audience_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('audience_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('audience_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('audience_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], name=op.f('audience_table_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs_table.program_id'], name=op.f('audience_table_program_id_fkey'), ondelete='SET NULL')
    )
    op.drop_table('event_audience_table')
    # ### end Alembic commands ###
