"""added officer table

Revision ID: bebe8401bdc9
Revises: 6f472bdbfc3e
Create Date: 2025-12-18 07:59:24.641683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bebe8401bdc9'
down_revision: Union[str, Sequence[str], None] = '6f472bdbfc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers_table',
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=False),
    sa.Column('assigned_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('oauth_id', sa.String(length=100), nullable=True),
    sa.Column('oauth_email', sa.String(length=250), nullable=False),
    sa.Column('oauth_image', sa.String(length=500), nullable=True),
    sa.Column('officer_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('officer_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('officer_id')
    )
    op.create_index(op.f('ix_officers_table_full_name'), 'officers_table', ['full_name'], unique=True)
    op.create_index(op.f('ix_officers_table_oauth_email'), 'officers_table', ['oauth_email'], unique=True)
    op.create_index(op.f('ix_officers_table_oauth_id'), 'officers_table', ['oauth_id'], unique=True)
    op.drop_column('departments_table', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_officers_table_oauth_id'), table_name='officers_table')
    op.drop_index(op.f('ix_officers_table_oauth_email'), table_name='officers_table')
    op.drop_index(op.f('ix_officers_table_full_name'), table_name='officers_table')
    op.drop_table('officers_table')
    # ### end Alembic commands ###
