"""_table

Revision ID: 6b3a54782a45
Revises: d79f2154cfdf
Create Date: 2025-12-29 21:19:51.109693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b3a54782a45'
down_revision: Union[str, Sequence[str], None] = 'd79f2154cfdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_schedules_table',
    sa.Column('event_schedule_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_schedule_label', sa.String(length=100), nullable=False),
    sa.Column('event_schedule_datetime_range', postgresql.TSTZRANGE(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_schedule_id')
    )
    op.drop_table('event_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_schedules',
    sa.Column('event_schedule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_schedule_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_schedule_datetime_range', postgresql.TSTZRANGE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], name=op.f('event_schedules_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_schedule_id', name=op.f('event_schedules_pkey'))
    )
    op.drop_table('event_schedules_table')
    # ### end Alembic commands ###
