"""init

Revision ID: a4507fd69d4c
Revises: 9fc09f830727
Create Date: 2025-12-15 21:39:48.465769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4507fd69d4c'
down_revision: Union[str, Sequence[str], None] = '9fc09f830727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments_table',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('department_name', sa.String(length=250), nullable=False),
    sa.Column('role', sa.Enum('school', 'department', name='department_role_enum'), nullable=False),
    sa.Column('department_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('department_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_departments_table_department_name'), 'departments_table', ['department_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_table_department_name'), table_name='departments_table')
    op.drop_table('departments_table')
    # ### end Alembic commands ###
