"""added unique index in lastname and firstname

Revision ID: ada003342b67
Revises: 3546a82af5d0
Create Date: 2025-12-28 12:56:47.438107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada003342b67'
down_revision: Union[str, Sequence[str], None] = '3546a82af5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_student_full_name', 'students_table', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_students_table_first_name'), 'students_table', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_table_last_name'), 'students_table', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_table_last_name'), table_name='students_table')
    op.drop_index(op.f('ix_students_table_first_name'), table_name='students_table')
    op.drop_index('ix_student_full_name', table_name='students_table')
    # ### end Alembic commands ###
