"""added scheduler in event

Revision ID: d79f2154cfdf
Revises: adffd0070a17
Create Date: 2025-12-29 21:15:58.163612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd79f2154cfdf'
down_revision: Union[str, Sequence[str], None] = 'adffd0070a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_schedules',
    sa.Column('event_schedule_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_schedule_label', sa.String(length=100), nullable=False),
    sa.Column('event_schedule_datetime_range', postgresql.TSTZRANGE(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_schedule_id')
    )
    op.add_column('events_table', sa.Column('event_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_table', 'event_updated_at')
    op.drop_table('event_schedules')
    # ### end Alembic commands ###
