"""added student model 2

Revision ID: b355a1da4814
Revises: 64d1018637c6
Create Date: 2025-12-15 22:13:16.433612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b355a1da4814'
down_revision: Union[str, Sequence[str], None] = '64d1018637c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_table',
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('student_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('student_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_table')
    # ### end Alembic commands ###
