"""remove event id

Revision ID: a931123a8191
Revises: 107664502f25
Create Date: 2025-12-27 23:14:56.753722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a931123a8191'
down_revision: Union[str, Sequence[str], None] = '107664502f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audience_table_event_id_fkey'), 'audience_table', type_='foreignkey')
    op.drop_column('audience_table', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience_table', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('audience_table_event_id_fkey'), 'audience_table', 'events_table', ['event_id'], ['event_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
