"""added program table

Revision ID: 690b04607142
Revises: bebe8401bdc9
Create Date: 2025-12-18 12:38:44.966222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690b04607142'
down_revision: Union[str, Sequence[str], None] = 'bebe8401bdc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs_table',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('program_name', sa.String(length=250), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.add_column('students_table', sa.Column('student_school_id', sa.String(length=100), nullable=False))
    op.add_column('students_table', sa.Column('student_image', sa.String(length=500), nullable=True))
    op.add_column('students_table', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('students_table', sa.Column('last_name', sa.String(length=150), nullable=False))
    op.alter_column('students_table', 'student_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_students_table_student_school_id'), 'students_table', ['student_school_id'], unique=True)
    op.drop_column('students_table', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_table', sa.Column('full_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_students_table_student_school_id'), table_name='students_table')
    op.alter_column('students_table', 'student_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('students_table', 'last_name')
    op.drop_column('students_table', 'first_name')
    op.drop_column('students_table', 'student_image')
    op.drop_column('students_table', 'student_school_id')
    op.drop_table('programs_table')
    # ### end Alembic commands ###
