"""int primary key if tag

Revision ID: 2c283af0a53e
Revises: 6b3a54782a45
Create Date: 2025-12-31 11:35:34.614449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c283af0a53e'
down_revision: Union[str, Sequence[str], None] = '6b3a54782a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tag_table', sa.Column('event_tag_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('event_tag_table', sa.Column('event_tag_name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('event_tag_table_tag_name_key'), 'event_tag_table', type_='unique')
    op.create_unique_constraint(None, 'event_tag_table', ['event_tag_name'])
    op.drop_column('event_tag_table', 'tag_id')
    op.drop_column('event_tag_table', 'tag_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_tag_table', sa.Column('tag_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('event_tag_table', sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_tag_table', type_='unique')
    op.create_unique_constraint(op.f('event_tag_table_tag_name_key'), 'event_tag_table', ['tag_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('event_tag_table', 'event_tag_name')
    op.drop_column('event_tag_table', 'event_tag_id')
    # ### end Alembic commands ###
