"""added program_code field in the program table

Revision ID: c59e2b373574
Revises: f272ee3749ef
Create Date: 2025-12-18 12:46:56.188712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59e2b373574'
down_revision: Union[str, Sequence[str], None] = 'f272ee3749ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs_table', sa.Column('program_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_programs_table_program_code'), 'programs_table', ['program_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programs_table_program_code'), table_name='programs_table')
    op.drop_column('programs_table', 'program_code')
    # ### end Alembic commands ###
