"""added event models

Revision ID: b9d658ef4337
Revises: c59e2b373574
Create Date: 2025-12-27 11:14:38.919752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d658ef4337'
down_revision: Union[str, Sequence[str], None] = 'c59e2b373574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_table',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_title', sa.String(length=250), nullable=False),
    sa.Column('event_content', sa.Text(), nullable=True),
    sa.Column('event_target_program_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('event_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_target_program_id'], ['programs_table.program_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('audience_table',
    sa.Column('audience_group_id', sa.UUID(), nullable=False),
    sa.Column('audience_group_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments_table.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs_table.program_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audience_group_id')
    )
    op.create_table('event_media_table',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('media_file_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('event_tag_table',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_tag_table')
    op.drop_table('event_media_table')
    op.drop_table('audience_table')
    op.drop_table('events_table')
    # ### end Alembic commands ###
