"""change oath compatable

Revision ID: 6f472bdbfc3e
Revises: 6fe18d8ed3f4
Create Date: 2025-12-17 17:50:58.357774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f472bdbfc3e'
down_revision: Union[str, Sequence[str], None] = '6fe18d8ed3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('oauth_id', sa.String(length=100), nullable=True))
    op.add_column('departments_table', sa.Column('oauth_email', sa.String(length=250), nullable=False))
    op.drop_index(op.f('ix_departments_table_google_email'), table_name='departments_table')
    op.drop_index(op.f('ix_departments_table_google_sub_id'), table_name='departments_table')
    op.create_index(op.f('ix_departments_table_oauth_email'), 'departments_table', ['oauth_email'], unique=True)
    op.create_index(op.f('ix_departments_table_oauth_id'), 'departments_table', ['oauth_id'], unique=True)
    op.drop_column('departments_table', 'google_email')
    op.drop_column('departments_table', 'google_sub_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('google_sub_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('departments_table', sa.Column('google_email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_departments_table_oauth_id'), table_name='departments_table')
    op.drop_index(op.f('ix_departments_table_oauth_email'), table_name='departments_table')
    op.create_index(op.f('ix_departments_table_google_sub_id'), 'departments_table', ['google_sub_id'], unique=True)
    op.create_index(op.f('ix_departments_table_google_email'), 'departments_table', ['google_email'], unique=True)
    op.drop_column('departments_table', 'oauth_email')
    op.drop_column('departments_table', 'oauth_id')
    # ### end Alembic commands ###
