"""remove google name and image

Revision ID: 6fe18d8ed3f4
Revises: 29f1c810b2da
Create Date: 2025-12-17 17:48:56.702907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe18d8ed3f4'
down_revision: Union[str, Sequence[str], None] = '29f1c810b2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments_table', 'google_image')
    op.drop_column('departments_table', 'google_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('google_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('departments_table', sa.Column('google_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
