"""added student model

Revision ID: 64d1018637c6
Revises: 8f93a635ea24
Create Date: 2025-12-15 22:12:15.975160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d1018637c6'
down_revision: Union[str, Sequence[str], None] = '8f93a635ea24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('department_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_departments_table_department_code'), 'departments_table', ['department_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_table_department_code'), table_name='departments_table')
    op.drop_column('departments_table', 'department_code')
    # ### end Alembic commands ###
