"""refactorm medias

Revision ID: 403b2be72f6d
Revises: 6cea1f294560
Create Date: 2025-12-31 12:24:11.814886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '403b2be72f6d'
down_revision: Union[str, Sequence[str], None] = '6cea1f294560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_media_images_table',
    sa.Column('event_media_image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_media_image_url', sa.String(length=500), nullable=False),
    sa.Column('event_media_image_like_count', sa.Integer(), nullable=False),
    sa.Column('event_media_image_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_media_image_id')
    )
    op.create_table('event_media_videos_table',
    sa.Column('event_media_video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_media_video_url', sa.String(length=500), nullable=False),
    sa.Column('event_media_view_count', sa.Integer(), nullable=False),
    sa.Column('event_media_video_reaction_score', sa.Integer(), nullable=False),
    sa.Column('event_media_video_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_media_video_id')
    )
    op.create_table('event_media_image_likes_table',
    sa.Column('event_media_image_like_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_media_image_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('event_media_image_like_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_media_image_id'], ['event_media_images_table.event_media_image_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_media_image_like_id'),
    sa.UniqueConstraint('event_media_image_id', 'student_id', name='_student_event_image_like_uc')
    )
    op.create_table('event_video_reactions_table',
    sa.Column('event_media_video_reaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_media_video_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('event_media_video_reaction_type', sa.Enum('like', 'love', 'fire', name='event_media_video_reaction_type_enum'), nullable=False),
    sa.Column('event_media_video_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_media_video_id'], ['event_media_videos_table.event_media_video_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_media_video_reaction_id'),
    sa.UniqueConstraint('event_media_video_id', 'student_id', name='_student_video_reaction_uc')
    )
    op.drop_table('event_media_table')
    op.add_column('events_table', sa.Column('enable_image_reactions', sa.Boolean(), nullable=False))
    op.add_column('events_table', sa.Column('enable_video_reactions', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_table', 'enable_video_reactions')
    op.drop_column('events_table', 'enable_image_reactions')
    op.create_table('event_media_table',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_media_file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('event_media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('event_media_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.event_id'], name=op.f('event_media_table_event_id_fkey'))
    )
    op.drop_table('event_video_reactions_table')
    op.drop_table('event_media_image_likes_table')
    op.drop_table('event_media_videos_table')
    op.drop_table('event_media_images_table')
    # ### end Alembic commands ###
