"""added timestamp in program

Revision ID: 444c147e65c0
Revises: b9d658ef4337
Create Date: 2025-12-27 18:59:24.948922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444c147e65c0'
down_revision: Union[str, Sequence[str], None] = 'b9d658ef4337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs_table', sa.Column('program_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('programs_table', sa.Column('program_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs_table', 'program_updated_at')
    op.drop_column('programs_table', 'program_created_at')
    # ### end Alembic commands ###
