"""added department image

Revision ID: 8f93a635ea24
Revises: a4507fd69d4c
Create Date: 2025-12-15 21:46:44.261355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f93a635ea24'
down_revision: Union[str, Sequence[str], None] = 'a4507fd69d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('department_image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments_table', 'department_image')
    # ### end Alembic commands ###
