"""ref student to program

Revision ID: f272ee3749ef
Revises: 7301bedbb60f
Create Date: 2025-12-18 12:43:34.630089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f272ee3749ef'
down_revision: Union[str, Sequence[str], None] = '7301bedbb60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_table', sa.Column('program_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'students_table', 'programs_table', ['program_id'], ['program_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_table', type_='foreignkey')
    op.drop_column('students_table', 'program_id')
    # ### end Alembic commands ###
