"""added google credentials

Revision ID: 29f1c810b2da
Revises: b355a1da4814
Create Date: 2025-12-17 08:54:49.076353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f1c810b2da'
down_revision: Union[str, Sequence[str], None] = 'b355a1da4814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments_table', sa.Column('google_sub_id', sa.String(length=100), nullable=True))
    op.add_column('departments_table', sa.Column('google_email', sa.String(length=250), nullable=False))
    op.add_column('departments_table', sa.Column('google_name', sa.String(length=250), nullable=False))
    op.add_column('departments_table', sa.Column('google_image', sa.String(length=500), nullable=True))
    op.add_column('departments_table', sa.Column('is_online', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_departments_table_google_email'), 'departments_table', ['google_email'], unique=True)
    op.create_index(op.f('ix_departments_table_google_sub_id'), 'departments_table', ['google_sub_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_table_google_sub_id'), table_name='departments_table')
    op.drop_index(op.f('ix_departments_table_google_email'), table_name='departments_table')
    op.drop_column('departments_table', 'is_online')
    op.drop_column('departments_table', 'google_image')
    op.drop_column('departments_table', 'google_name')
    op.drop_column('departments_table', 'google_email')
    op.drop_column('departments_table', 'google_sub_id')
    # ### end Alembic commands ###
