"""remove _group

Revision ID: 107664502f25
Revises: 444c147e65c0
Create Date: 2025-12-27 23:08:37.342131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107664502f25'
down_revision: Union[str, Sequence[str], None] = '444c147e65c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience_table', sa.Column('audience_id', sa.UUID(), nullable=False))
    op.add_column('audience_table', sa.Column('audience_name', sa.String(length=100), nullable=False))
    op.add_column('audience_table', sa.Column('audience_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audience_table', sa.Column('audience_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('audience_table', 'audience_group_id')
    op.drop_column('audience_table', 'audience_group_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience_table', sa.Column('audience_group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('audience_table', sa.Column('audience_group_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('audience_table', 'audience_updated_at')
    op.drop_column('audience_table', 'audience_created_at')
    op.drop_column('audience_table', 'audience_name')
    op.drop_column('audience_table', 'audience_id')
    # ### end Alembic commands ###
